// Package emit is the Phase 0 C backend. It lowers a type-checked ast.File to a
// single self-contained C translation unit — the shortest path to a binary, and
// the thesis the roadmap's Phase 0 proves (lex -> parse -> sema -> emit C -> cc).
//
// Every Zerg name is emitted with a 'zg_' prefix so it cannot collide with a C
// keyword or the C runtime; the Zerg 'main' becomes 'zg_main', wrapped by a real C
// 'main'. The type universe maps int->int64_t, float->double, bool->bool (stdbool),
// str->const char*. There is no runtime yet: strings are C string literals and
// nothing is refcounted (Phase 0 leaks, per the roadmap).
package emit

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/cmj0121/zerg/src/bootstrap/internal/ast"
	"github.com/cmj0121/zerg/src/bootstrap/internal/diag"
	"github.com/cmj0121/zerg/src/bootstrap/internal/sema"
	"github.com/cmj0121/zerg/src/bootstrap/internal/token"
)

// Emit lowers the file to C source. When the returned diagnostics are non-empty
// the source is empty and must not be compiled.
func Emit(file *ast.File, info *sema.Info) (string, []diag.Diagnostic) {
	e := &emitter{info: info}
	e.program(file)
	if !e.diags.Empty() {
		return "", e.diags.Items()
	}
	return e.sb.String(), nil
}

type emitter struct {
	info   *sema.Info
	sb     strings.Builder
	indent int
	diags  diag.List
}

func (e *emitter) program(file *ast.File) {
	main, ok := e.info.Funcs["main"]
	switch {
	case !ok:
		e.diags.Add(token.Span{}, "no 'main' function to build a program")
		return
	case len(main.Params) != 0:
		e.diags.Add(main.Decl.Span, "'main' must take no parameters in Phase 0")
	case main.Ret != sema.Nil && main.Ret != sema.Int:
		e.diags.Add(main.Decl.Span, "'main' must return nil or int in Phase 0")
	}

	e.line("// Generated by zergc (Phase 0). Do not edit.")
	e.line("#include <stdio.h>")
	e.line("#include <stdint.h>")
	e.line("#include <stdbool.h>")
	e.blank()

	// prototypes first, so declaration order does not constrain calls
	for _, fn := range funcs(file) {
		e.raw(e.signature(fn))
		e.rawln(";")
	}
	e.blank()

	for _, fn := range funcs(file) {
		e.function(fn)
		e.blank()
	}

	e.cMain(main)
}

// funcs returns the function declarations in source order.
func funcs(file *ast.File) []*ast.FuncDecl {
	var out []*ast.FuncDecl
	for _, d := range file.Decls {
		if fn, ok := d.(*ast.FuncDecl); ok {
			out = append(out, fn)
		}
	}
	return out
}

// signature renders 'ret zg_name(params)' without a trailing token.
func (e *emitter) signature(fn *ast.FuncDecl) string {
	sig := e.info.Funcs[fn.Name]
	var params strings.Builder
	if len(sig.Params) == 0 {
		params.WriteString("void")
	} else {
		for i, pt := range sig.Params {
			if i > 0 {
				params.WriteString(", ")
			}
			fmt.Fprintf(&params, "%s zg_%s", cType(pt), sig.ParamNames[i])
		}
	}
	return fmt.Sprintf("%s zg_%s(%s)", cType(sig.Ret), fn.Name, params.String())
}

func (e *emitter) function(fn *ast.FuncDecl) {
	sig := e.info.Funcs[fn.Name]
	e.raw(e.signature(fn))
	e.rawln(" {")
	e.indent++
	for _, s := range fn.Body.Stmts {
		e.stmt(s)
	}
	// guarantee a return value on every path for value-returning functions
	if sig.Ret != sema.Nil {
		e.line("return " + zeroValue(sig.Ret) + ";")
	}
	e.indent--
	e.line("}")
}

// cMain wraps zg_main in a C entry point.
func (e *emitter) cMain(main *sema.FuncSig) {
	e.line("int main(void) {")
	e.indent++
	if main.Ret == sema.Int {
		e.line("return (int)zg_main();")
	} else {
		e.line("zg_main();")
		e.line("return 0;")
	}
	e.indent--
	e.line("}")
}

// --- statements ---------------------------------------------------------------

func (e *emitter) stmt(s ast.Stmt) {
	switch n := s.(type) {
	case *ast.NopStmt:
		e.line(";")
	case *ast.BindStmt:
		t := e.info.BindTypes[n]
		e.line(fmt.Sprintf("%s zg_%s = %s;", cType(t), n.Name, e.expr(n.Value)))
	case *ast.AssignStmt:
		e.line(fmt.Sprintf("zg_%s = %s;", n.Name, e.expr(n.Value)))
	case *ast.PrintStmt:
		e.printStmt(n)
	case *ast.ReturnStmt:
		if n.Value == nil {
			e.line("return;")
		} else {
			e.line("return " + e.expr(n.Value) + ";")
		}
	case *ast.BreakStmt:
		e.line("break;")
	case *ast.ContinueStmt:
		e.line("continue;")
	case *ast.IfStmt:
		e.ifStmt(n)
	case *ast.ForStmt:
		e.forStmt(n)
	case *ast.ExprStmt:
		e.line(e.expr(n.X) + ";")
	}
}

func (e *emitter) printStmt(n *ast.PrintStmt) {
	v := e.expr(n.Value)
	switch e.info.ExprTypes[n.Value] {
	case sema.Int:
		e.line(fmt.Sprintf("printf(\"%%lld\\n\", (long long)(%s));", v))
	case sema.Float:
		e.line(fmt.Sprintf("printf(\"%%g\\n\", %s);", v))
	case sema.Bool:
		e.line(fmt.Sprintf("printf(\"%%s\\n\", (%s) ? \"true\" : \"false\");", v))
	case sema.Str:
		e.line(fmt.Sprintf("printf(\"%%s\\n\", %s);", v))
	}
}

func (e *emitter) ifStmt(n *ast.IfStmt) {
	for i, br := range n.Branches {
		kw := "if"
		if i > 0 {
			kw = "} else if"
		}
		e.line(fmt.Sprintf("%s (%s) {", kw, e.expr(br.Cond)))
		e.body(br.Body)
	}
	if n.Else != nil {
		e.line("} else {")
		e.body(n.Else)
	}
	e.line("}")
}

func (e *emitter) forStmt(n *ast.ForStmt) {
	if n.Cond == nil {
		e.line("for (;;) {")
	} else {
		e.line(fmt.Sprintf("while (%s) {", e.expr(n.Cond)))
	}
	e.body(n.Body)
	e.line("}")
}

// body emits a block's statements at one deeper indent (the surrounding braces are
// emitted by the caller so 'else' can share a line with the closing brace).
func (e *emitter) body(b *ast.Block) {
	e.indent++
	for _, s := range b.Stmts {
		e.stmt(s)
	}
	e.indent--
}

// --- expressions --------------------------------------------------------------

func (e *emitter) expr(x ast.Expr) string {
	switch n := x.(type) {
	case *ast.IntLit:
		return strconv.FormatInt(n.Value, 10)
	case *ast.FloatLit:
		return floatLiteral(n.Value)
	case *ast.BoolLit:
		if n.Value {
			return "true"
		}
		return "false"
	case *ast.StrLit:
		return cString(n.Value)
	case *ast.NilLit:
		return "0"
	case *ast.Ident:
		return "zg_" + n.Name
	case *ast.Unary:
		return fmt.Sprintf("(%s%s)", unaryOp(n.Op), e.expr(n.X))
	case *ast.Binary:
		return fmt.Sprintf("(%s %s %s)", e.expr(n.L), binaryOp(n.Op), e.expr(n.R))
	case *ast.Call:
		return e.call(n)
	default:
		return "0"
	}
}

func (e *emitter) call(n *ast.Call) string {
	name := n.Callee.(*ast.Ident).Name
	var args strings.Builder
	for i, a := range n.Args {
		if i > 0 {
			args.WriteString(", ")
		}
		args.WriteString(e.expr(a))
	}
	return fmt.Sprintf("zg_%s(%s)", name, args.String())
}

// --- lowering helpers ---------------------------------------------------------

func cType(t sema.Type) string {
	switch t {
	case sema.Int:
		return "int64_t"
	case sema.Float:
		return "double"
	case sema.Bool:
		return "bool"
	case sema.Str:
		return "const char*"
	default:
		return "void"
	}
}

func zeroValue(t sema.Type) string {
	switch t {
	case sema.Int:
		return "0"
	case sema.Float:
		return "0.0"
	case sema.Bool:
		return "false"
	case sema.Str:
		return "\"\""
	default:
		return "0"
	}
}

func unaryOp(k token.Kind) string {
	switch k {
	case token.Minus, token.MinusMod:
		return "-"
	case token.Not:
		return "!"
	case token.Tilde:
		return "~"
	}
	return "?"
}

func binaryOp(k token.Kind) string {
	switch k {
	case token.Plus, token.PlusMod:
		return "+"
	case token.Minus, token.MinusMod:
		return "-"
	case token.Star, token.StarMod:
		return "*"
	case token.Slash:
		return "/"
	case token.Percent:
		return "%"
	case token.Amp:
		return "&"
	case token.Pipe:
		return "|"
	case token.Caret:
		return "^"
	case token.Shl:
		return "<<"
	case token.Shr:
		return ">>"
	case token.EqEq:
		return "=="
	case token.Ne:
		return "!="
	case token.Lt:
		return "<"
	case token.Gt:
		return ">"
	case token.Le:
		return "<="
	case token.Ge:
		return ">="
	case token.And:
		return "&&"
	case token.Or:
		return "||"
	}
	return "?"
}

// floatLiteral renders a double literal that C reads as floating-point (always
// carrying a '.' or exponent).
func floatLiteral(v float64) string {
	s := strconv.FormatFloat(v, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eEnN") { // n/N guards inf/nan spellings
		s += ".0"
	}
	return s
}

// cString renders a Go string as a C string literal, escaping conservatively with
// octal for bytes outside printable ASCII so no '\x' run-on can occur.
func cString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c == '\n':
			b.WriteString("\\n")
		case c == '\t':
			b.WriteString("\\t")
		case c == '\r':
			b.WriteString("\\r")
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// --- output helpers -----------------------------------------------------------

func (e *emitter) line(s string) {
	e.writeIndent()
	e.sb.WriteString(s)
	e.sb.WriteByte('\n')
}

func (e *emitter) raw(s string) {
	e.writeIndent()
	e.sb.WriteString(s)
}

func (e *emitter) rawln(s string) {
	e.sb.WriteString(s)
	e.sb.WriteByte('\n')
}

func (e *emitter) blank() { e.sb.WriteByte('\n') }

func (e *emitter) writeIndent() {
	for i := 0; i < e.indent; i++ {
		e.sb.WriteString("    ")
	}
}
