// Package emit is the Phase 0 C backend. It lowers a type-checked ast.File to a
// single self-contained C translation unit — the shortest path to a binary, and
// the thesis the roadmap's Phase 0 proves (lex -> parse -> sema -> emit C -> cc).
//
// Every Zerg name is emitted with a 'zg_' prefix so it cannot collide with a C
// keyword or the C runtime; the Zerg 'main' becomes 'zg_main', wrapped by a real C
// 'main'. The type universe maps int->int64_t, float->double, bool->bool (stdbool),
// str->const char*. There is no runtime yet: strings are C string literals and
// nothing is refcounted (Phase 0 leaks, per the roadmap).
package emit

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/cmj0121/zerg/src/bootstrap/internal/ast"
	"github.com/cmj0121/zerg/src/bootstrap/internal/diag"
	"github.com/cmj0121/zerg/src/bootstrap/internal/mono"
	"github.com/cmj0121/zerg/src/bootstrap/internal/sema"
	"github.com/cmj0121/zerg/src/bootstrap/internal/token"
	"github.com/cmj0121/zerg/src/bootstrap/internal/types"
)

// Emit lowers the monomorphized program to C source. It renders each instance in
// prog.Funcs, reading the type overlay from prog.Info. When the returned
// diagnostics are non-empty the source is empty and must not be compiled.
func Emit(prog *mono.Program) (string, []diag.Diagnostic) {
	e := &emitter{prog: prog, info: prog.Info}
	e.program()
	if !e.diags.Empty() {
		return "", e.diags.Items()
	}
	return e.sb.String(), nil
}

type emitter struct {
	prog   *mono.Program
	info   *sema.Info
	cur    *mono.Instance // the instance whose body is being rendered (its type overlay)
	sb     strings.Builder
	indent int
	diags  diag.List

	// Per-function name environment. Zerg allows a binding to shadow an outer
	// name (e.g. 'mut n := n'), but C parameters and the top-level body share one
	// scope, so every local gets a unique C name; 'scopes' maps a source name to
	// the C name currently in effect and 'used' guarantees uniqueness.
	scopes  []map[string]string
	used    map[string]bool
	counter int
}

func (e *emitter) program() {
	main, ok := e.info.Funcs["main"]
	switch {
	case !ok:
		e.diags.Add(token.Span{}, "no 'main' function to build a program")
		return
	case len(main.Params) != 0:
		e.diags.Add(main.Decl.Span(), "'main' must take no parameters in Phase 0")
	case main.Ret != sema.Nil && main.Ret != sema.Int:
		e.diags.Add(main.Decl.Span(), "'main' must return nil or int in Phase 0")
	}

	e.line("// Generated by zerg (Phase 0). Do not edit.")
	e.line("#include <stdio.h>")
	e.line("#include <stdint.h>")
	e.line("#include <stdbool.h>")
	e.line("#include <string.h>")
	e.blank()

	// specialized nominal types, each before the functions that use it
	for _, ti := range e.prog.Types {
		e.typedef(ti)
	}

	// '#[dyn]' witness-table struct types, before any prototype that names one
	e.witnessStructs()

	// prototypes first, so declaration order does not constrain calls
	for _, inst := range e.prog.Funcs {
		e.line(e.prototype(inst) + ";")
	}
	e.blank()

	// concrete witness tables, after the impl-method prototypes their slots name
	e.witnessGlobals()

	for _, inst := range e.prog.Funcs {
		e.function(inst)
		e.blank()
	}

	e.cMain(main)
}

// typedef emits a specialized nominal type: a struct as a plain C struct, or an
// enum as a tagged union (an integer tag plus a union of the payload variants).
func (e *emitter) typedef(ti *mono.TypeInstance) {
	if ti.IsEnum {
		e.enumTypedef(ti)
		return
	}
	e.line("typedef struct {")
	e.indent++
	for _, f := range ti.Fields {
		e.line(e.ctype(f.Type) + " zg_" + f.Name + ";")
	}
	e.indent--
	e.line("} " + ti.Mangled + ";")
	e.blank()
}

// enumTypedef emits a specialized enum as a tagged union: an 'int32_t tag' holding
// the variant's zero-based discriminant, and, when any variant carries a payload, a
// union 'u' of one anonymous struct per payload variant whose fields are 'f0, f1,
// …'. A wholly fieldless enum emits the tag alone.
func (e *emitter) enumTypedef(ti *mono.TypeInstance) {
	e.line("typedef struct {")
	e.indent++
	e.line("int32_t tag;")
	if enumHasPayload(ti) {
		e.line("union {")
		e.indent++
		for _, v := range ti.Variants {
			if len(v.Payload) == 0 {
				continue
			}
			var b strings.Builder
			b.WriteString("struct { ")
			for i, pt := range v.Payload {
				fmt.Fprintf(&b, "%s f%d; ", e.ctype(pt), i)
			}
			b.WriteString("} " + v.Name + ";")
			e.line(b.String())
		}
		e.indent--
		e.line("} u;")
	}
	e.indent--
	e.line("} " + ti.Mangled + ";")
	e.blank()
}

// enumHasPayload reports whether any variant of an enum instance carries a payload,
// so a wholly fieldless enum omits the (empty, and in C ill-formed) union.
func enumHasPayload(ti *mono.TypeInstance) bool {
	for _, v := range ti.Variants {
		if len(v.Payload) > 0 {
			return true
		}
	}
	return false
}

// paramList renders a C parameter list ("void" when empty), formatting each of
// the n parameters with render.
func paramList(n int, render func(i int) string) string {
	if n == 0 {
		return "void"
	}
	var b strings.Builder
	for i := 0; i < n; i++ {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(render(i))
	}
	return b.String()
}

// prototype renders a forward declaration with parameter types only, using the
// instance's mangled C name and its concrete (specialized) signature.
func (e *emitter) prototype(inst *mono.Instance) string {
	if inst.Dyn || inst.RecvErased {
		return e.erasedSignature(inst, false)
	}
	params := paramList(len(inst.Params), func(i int) string { return e.paramType(inst.Params[i]) })
	return fmt.Sprintf("%s %s(%s)", e.ctype(inst.Ret), inst.Mangled, params)
}

func (e *emitter) function(inst *mono.Instance) {
	if inst.Dyn {
		e.dynFunction(inst)
		return
	}
	if inst.RecvErased {
		e.methodFunction(inst)
		return
	}
	fn := inst.Origin
	e.cur = inst
	e.used = map[string]bool{}
	e.counter = 0
	e.pushScope() // parameter scope

	params := paramList(len(inst.Params), func(i int) string {
		return e.paramType(inst.Params[i]) + " " + e.declareName(inst.ParamNames[i])
	})
	e.line(fmt.Sprintf("%s %s(%s) {", e.ctype(inst.Ret), inst.Mangled, params))

	e.indent++
	e.pushScope() // body scope, nested so a body binding can shadow a parameter
	for _, s := range fn.Body.Stmts {
		e.stmt(s)
	}
	e.popScope()
	// guarantee a return value on every path for value-returning functions
	if inst.Ret != sema.Nil && !endsWithReturn(fn.Body) {
		e.line("return " + zeroValue(inst.Ret) + ";")
	}
	e.indent--
	e.line("}")

	e.popScope()
}

// endsWithReturn reports whether a block's last statement is an unconditional
// return (a 'return ... if c' may fall through, so it does not count).
func endsWithReturn(b *ast.Block) bool {
	if len(b.Stmts) == 0 {
		return false
	}
	r, ok := b.Stmts[len(b.Stmts)-1].(*ast.ReturnStmt)
	return ok && r.Cond == nil
}

// cMain wraps zg_main in a C entry point.
func (e *emitter) cMain(main *sema.FuncSig) {
	e.line("int main(void) {")
	e.indent++
	if main.Ret == sema.Int {
		e.line("return (int)zg_main();")
	} else {
		e.line("zg_main();")
		e.line("return 0;")
	}
	e.indent--
	e.line("}")
}

// --- statements ---------------------------------------------------------------

func (e *emitter) stmt(s ast.Stmt) {
	switch n := s.(type) {
	case *ast.NopStmt:
		e.line(";")
	case *ast.BindStmt:
		t := e.cur.BindType(e.info, n)
		// resolve the RHS before declaring the name, so 'mut n := n' reads the
		// outer binding (matching ':=' semantics)
		rhs := e.expr(n.Value)
		e.line(e.localDecl(t, e.declareName(n.Name)) + " = " + rhs + ";")
	case *ast.Reassign:
		e.line(fmt.Sprintf("%s = %s;", e.assignTarget(n.Target), e.expr(n.Value)))
	case *ast.PrintStmt:
		e.printStmt(n)
	case *ast.ReturnStmt:
		ret := "return;"
		if n.Value != nil {
			ret = "return " + e.expr(n.Value) + ";"
		}
		if n.Cond != nil {
			e.line(fmt.Sprintf("if (%s) { %s }", e.expr(n.Cond), ret))
		} else {
			e.line(ret)
		}
	case *ast.BreakStmt:
		e.line("break;")
	case *ast.ContinueStmt:
		e.line("continue;")
	case *ast.IfStmt:
		e.ifStmt(n)
	case *ast.ForStmt:
		e.forStmt(n)
	case *ast.ExprStmt:
		e.line(e.expr(n.X) + ";")
	}
}

func (e *emitter) printStmt(n *ast.PrintStmt) {
	v := e.expr(n.Value)
	switch e.cur.ExprType(e.info, n.Value) {
	case sema.Int:
		e.line(fmt.Sprintf("printf(\"%%lld\\n\", (long long)(%s));", v))
	case sema.Float:
		e.line(fmt.Sprintf("printf(\"%%g\\n\", %s);", v))
	case sema.Bool:
		e.line(fmt.Sprintf("printf(\"%%s\\n\", (%s) ? \"true\" : \"false\");", v))
	case sema.Str:
		e.line(fmt.Sprintf("printf(\"%%s\\n\", %s);", v))
	}
}

func (e *emitter) ifStmt(n *ast.IfStmt) {
	for i, br := range n.Branches {
		kw := "if"
		if i > 0 {
			kw = "} else if"
		}
		e.line(fmt.Sprintf("%s (%s) {", kw, e.expr(br.Cond)))
		e.body(br.Body)
	}
	if n.Else != nil {
		e.line("} else {")
		e.body(n.Else)
	}
	e.line("}")
}

func (e *emitter) forStmt(n *ast.ForStmt) {
	if n.Cond == nil {
		e.line("for (;;) {")
	} else {
		e.line(fmt.Sprintf("while (%s) {", e.expr(n.Cond)))
	}
	e.body(n.Body)
	e.line("}")
}

// body emits a block's statements at one deeper indent (the surrounding braces are
// emitted by the caller so 'else' can share a line with the closing brace). It
// opens a nested name scope so the block's bindings do not leak.
func (e *emitter) body(b *ast.Block) {
	e.indent++
	e.pushScope()
	for _, s := range b.Stmts {
		e.stmt(s)
	}
	e.popScope()
	e.indent--
}

// --- name environment ---------------------------------------------------------

func (e *emitter) pushScope() { e.scopes = append(e.scopes, map[string]string{}) }
func (e *emitter) popScope()  { e.scopes = e.scopes[:len(e.scopes)-1] }

// declareName maps a source name to a fresh, function-unique C name (plain
// 'zg_<name>' unless that is already taken, in which case a numeric suffix is
// appended) and records it in the current scope.
func (e *emitter) declareName(name string) string {
	unique := "zg_" + name
	for e.used[unique] {
		e.counter++
		unique = fmt.Sprintf("zg_%s__%d", name, e.counter)
	}
	e.used[unique] = true
	e.scopes[len(e.scopes)-1][name] = unique
	return unique
}

// resolve returns the C name a source name currently refers to.
func (e *emitter) resolve(name string) string {
	for i := len(e.scopes) - 1; i >= 0; i-- {
		if u, ok := e.scopes[i][name]; ok {
			return u
		}
	}
	return "zg_" + name // unreachable for a checked program
}

// --- expressions --------------------------------------------------------------

func (e *emitter) expr(x ast.Expr) string {
	switch n := x.(type) {
	case *ast.IntLit:
		return strconv.FormatInt(n.Value, 10)
	case *ast.FloatLit:
		return floatLiteral(n.Value)
	case *ast.BoolLit:
		if n.Value {
			return "true"
		}
		return "false"
	case *ast.StrLit:
		return cString(n.Value)
	case *ast.NilLit:
		return "0"
	case *ast.Ident:
		if sym, ok := e.info.Refs[n]; ok && sym.Kind == sema.SymVariant {
			return e.constructVariant(n, nil, sym.Variant.Name)
		}
		return e.resolve(n.Name)
	case *ast.Unary:
		return fmt.Sprintf("(%s%s)", unaryOp(n.Op), e.expr(n.X))
	case *ast.Binary:
		return fmt.Sprintf("(%s %s %s)", e.expr(n.L), binaryOp(n.Op), e.expr(n.R))
	case *ast.Call:
		return e.call(n)
	case *ast.Field:
		return e.expr(n.X) + ".zg_" + n.Name
	case *ast.Bracket:
		if e.info.Brackets[n].Kind == sema.BracketIndex && len(n.Elems) == 1 {
			return e.expr(n.Base) + "[" + e.expr(n.Elems[0]) + "]"
		}
		return "0"
	case *ast.ListLit:
		return "{" + e.exprList(n.Elems) + "}"
	case *ast.MatchExpr:
		return e.lowerMatch(n)
	default:
		return "0"
	}
}

// exprList renders a comma-separated list of expressions.
func (e *emitter) exprList(xs []ast.Expr) string {
	var b strings.Builder
	for i, x := range xs {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(e.expr(x))
	}
	return b.String()
}

// lowerMatch lowers a match to a nested C ternary. The subject is a name or
// literal (a Phase 0 restriction), so it is safe to reference in each arm without
// hoisting. The last arm is an unguarded catch-all, forming the final else.
func (e *emitter) lowerMatch(m *ast.MatchExpr) string {
	subj := e.expr(m.Subject)
	subjT := e.cur.ExprType(e.info, m.Subject)
	n := len(m.Arms)
	result := e.armValue(m.Arms[n-1], subj, subjT)
	for i := n - 2; i >= 0; i-- {
		test, body := e.armTestAndValue(m.Arms[i], subj, subjT)
		result = fmt.Sprintf("(%s ? %s : %s)", test, body, result)
	}
	return result
}

// armValue emits an arm's body with the pattern's names bound to the subject.
func (e *emitter) armValue(arm ast.MatchArm, subj string, subjT sema.Type) string {
	pop := e.bindArm(arm.Pat, subj)
	v := e.expr(arm.Body)
	pop()
	return v
}

// armTestAndValue emits an arm's match test and body, with the pattern's names in
// scope for both the guard and the body.
func (e *emitter) armTestAndValue(arm ast.MatchArm, subj string, subjT sema.Type) (test, body string) {
	pop := e.bindArm(arm.Pat, subj)
	test = e.patternTest(arm.Pat, subj, subjT)
	if arm.Guard != nil {
		g := e.expr(arm.Guard)
		if test == "" {
			test = g
		} else {
			test = fmt.Sprintf("(%s && %s)", test, g)
		}
	}
	body = e.expr(arm.Body)
	pop()
	if test == "" {
		test = "1" // a non-last unguarded catch-all is rejected by sema
	}
	return test, body
}

// bindArm opens a scope and binds an arm pattern's names to the subject: a
// binding NamePattern binds the whole subject, and a variant pattern binds each
// payload name to its union field 'subj.u.<Variant>.f<i>'. It returns the scope's
// pop, to be deferred after the body is emitted.
func (e *emitter) bindArm(pat ast.Pattern, subj string) func() {
	e.pushScope()
	scope := e.scopes[len(e.scopes)-1]
	switch p := pat.(type) {
	case *ast.NamePattern:
		if res, ok := e.info.Patterns[p]; !ok || res.Kind != sema.NameVariant {
			scope[p.Name] = subj
		}
	case *ast.VariantPattern:
		for i, el := range p.Elems {
			if np, ok := el.(*ast.NamePattern); ok {
				scope[np.Name] = fmt.Sprintf("%s.u.%s.f%d", subj, p.Name, i)
			}
		}
	}
	return e.popScope
}

// patternTest renders the boolean C test for a pattern, or "" when the pattern
// matches unconditionally (wildcard or a bare binding). A literal compares by value
// (or strcmp for a string); a variant pattern — spelled 'V(...)' or a nullary 'V'
// name — compares the subject's tag.
func (e *emitter) patternTest(pat ast.Pattern, subj string, subjT sema.Type) string {
	switch p := pat.(type) {
	case *ast.LitPattern:
		lit := e.expr(p.Lit)
		if p.Neg {
			lit = "(-" + lit + ")"
		}
		if subjT == sema.Str {
			return fmt.Sprintf("(strcmp(%s, %s) == 0)", subj, lit)
		}
		return fmt.Sprintf("(%s == %s)", subj, lit)
	case *ast.VariantPattern:
		return fmt.Sprintf("(%s.tag == %d)", subj, e.variantTag(subjT, p.Name))
	case *ast.NamePattern:
		if res, ok := e.info.Patterns[p]; ok && res.Kind == sema.NameVariant {
			return fmt.Sprintf("(%s.tag == %d)", subj, e.variantTag(subjT, p.Name))
		}
	}
	return ""
}

// variantTag returns the discriminant of a named variant of an enum subject, read
// from the specialized enum instance (0 when the type or variant is not found, a
// case a checked program does not reach).
func (e *emitter) variantTag(subjT sema.Type, name string) int {
	if ti := e.prog.EnumInstance(subjT); ti != nil {
		if v, ok := ti.Variant(name); ok {
			return v.Tag
		}
	}
	return 0
}

func (e *emitter) call(n *ast.Call) string {
	if site, ok := e.cur.DynSites[n]; ok {
		return e.dynCallSite(n, site)
	}
	if e.cur.Dyn {
		if s := e.dynDispatch(n); s != "" {
			return s
		}
	}
	id, _ := n.Callee.(*ast.Ident)
	if id != nil {
		if sym, ok := e.info.Refs[id]; ok {
			switch sym.Kind {
			case sema.SymType:
				return e.construct(n)
			case sema.SymVariant:
				return e.constructVariant(n, n.Args, sym.Variant.Name)
			}
		}
	}
	var args strings.Builder
	for i, a := range n.Args {
		if i > 0 {
			args.WriteString(", ")
		}
		args.WriteString(e.expr(a.Value))
	}
	return fmt.Sprintf("%s(%s)", e.callTarget(n, id), args.String())
}

// callTarget is the mangled C name a call resolves to: a generic call site is
// recorded per instance (so the same call in two specializations dispatches to two
// callees); a non-generic call falls back to the program-level 'zg_<name>'.
func (e *emitter) callTarget(n *ast.Call, id *ast.Ident) string {
	if m, ok := e.cur.Calls[n]; ok {
		return m
	}
	return e.prog.CallTarget(id.Name)
}

// construct lowers a struct construction 'T(...)' to a C compound literal of the
// specialized struct type, with arguments in field-declaration order.
func (e *emitter) construct(n *ast.Call) string {
	name := e.ctype(e.cur.ExprType(e.info, n))
	return "((" + name + "){" + e.constructArgs(n.Args) + "})"
}

// constructVariant lowers an enum variant used as a value — a payload
// construction 'V(a, b)' or a bare nullary value 'V' — to a C compound literal of
// the specialized tagged union: the variant's tag, and, for a payload variant, its
// arguments in the union member 'u.<V>' as fields 'f0, f1, …'. node is the
// construction expression (used to read its concrete enum type).
func (e *emitter) constructVariant(node ast.Expr, args []ast.Arg, name string) string {
	t := e.cur.ExprType(e.info, node)
	cname := e.ctype(t)
	tag := 0
	if ti := e.prog.EnumInstance(t); ti != nil {
		if v, ok := ti.Variant(name); ok {
			tag = v.Tag
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "((%s){.tag = %d", cname, tag)
	if len(args) > 0 {
		fmt.Fprintf(&b, ", .u.%s = {", name)
		for i, a := range args {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, ".f%d = %s", i, e.expr(a.Value))
		}
		b.WriteString("}")
	}
	b.WriteString("})")
	return b.String()
}

// constructArgs renders a construction's positional argument values in order.
func (e *emitter) constructArgs(args []ast.Arg) string {
	var b strings.Builder
	for i, a := range args {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(e.expr(a.Value))
	}
	return b.String()
}

// assignTarget lowers a reassignment target. The Phase 0 backend only lowers the
// bare-identifier lvalue that the checked examples use; richer shapes (tuple,
// struct, field, index) are outside the Phase 0 subset.
func (e *emitter) assignTarget(t ast.AssignTarget) string {
	if lv, ok := t.(*ast.LValueTarget); ok {
		return e.expr(lv.X)
	}
	return "0"
}

// --- lowering helpers ---------------------------------------------------------

// ctype renders a type in type-only position (a return type, a cast, a field, a
// struct-typed value): a specialized nominal type spells its mangled C name, and
// every other type falls to the primitive mapping — so a non-generic program's C is
// unchanged.
func (e *emitter) ctype(t sema.Type) string {
	if name, ok := e.prog.TypeName(t); ok {
		return name
	}
	return cType(t)
}

// paramType renders a parameter's C type. A fixed-size array parameter decays to a
// pointer to its element (C cannot pass an array by value); every other type is its
// ctype.
func (e *emitter) paramType(t sema.Type) string {
	if a, ok := t.(*types.Array); ok {
		return e.ctype(a.Elem) + "*"
	}
	return e.ctype(t)
}

// localDecl renders a local declaration 'type name'. A fixed-size array places its
// bound after the name ('int64_t name[N]'), the C array declarator; every other
// type is 'ctype name', identical to the pre-generics backend.
func (e *emitter) localDecl(t sema.Type, name string) string {
	if a, ok := t.(*types.Array); ok && a.N.Known {
		return e.ctype(a.Elem) + " " + name + "[" + strconv.FormatInt(a.N.I, 10) + "]"
	}
	return e.ctype(t) + " " + name
}

func cType(t sema.Type) string {
	switch t {
	case sema.Int:
		return "int64_t"
	case sema.Float:
		return "double"
	case sema.Bool:
		return "bool"
	case sema.Str:
		return "const char*"
	default:
		return "void"
	}
}

func zeroValue(t sema.Type) string {
	switch t {
	case sema.Int:
		return "0"
	case sema.Float:
		return "0.0"
	case sema.Bool:
		return "false"
	case sema.Str:
		return "\"\""
	default:
		return "0"
	}
}

func unaryOp(k token.Kind) string {
	switch k {
	case token.Minus, token.MinusMod:
		return "-"
	case token.Not:
		return "!"
	case token.Tilde:
		return "~"
	}
	return "?"
}

func binaryOp(k token.Kind) string {
	switch k {
	case token.Plus, token.PlusMod:
		return "+"
	case token.Minus, token.MinusMod:
		return "-"
	case token.Star, token.StarMod:
		return "*"
	case token.Slash:
		return "/"
	case token.Percent:
		return "%"
	case token.Amp:
		return "&"
	case token.Pipe:
		return "|"
	case token.Caret:
		return "^"
	case token.Shl:
		return "<<"
	case token.Shr:
		return ">>"
	case token.EqEq:
		return "=="
	case token.Ne:
		return "!="
	case token.Lt:
		return "<"
	case token.Gt:
		return ">"
	case token.Le:
		return "<="
	case token.Ge:
		return ">="
	case token.And:
		return "&&"
	case token.Or:
		return "||"
	}
	return "?"
}

// floatLiteral renders a double literal that C reads as floating-point (always
// carrying a '.' or exponent).
func floatLiteral(v float64) string {
	s := strconv.FormatFloat(v, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eEnN") { // n/N guards inf/nan spellings
		s += ".0"
	}
	return s
}

// cString renders a Go string as a C string literal, escaping conservatively with
// octal for bytes outside printable ASCII so no '\x' run-on can occur.
func cString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c == '\n':
			b.WriteString("\\n")
		case c == '\t':
			b.WriteString("\\t")
		case c == '\r':
			b.WriteString("\\r")
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// --- output helpers -----------------------------------------------------------

func (e *emitter) line(s string) {
	e.writeIndent()
	e.sb.WriteString(s)
	e.sb.WriteByte('\n')
}

func (e *emitter) blank() { e.sb.WriteByte('\n') }

func (e *emitter) writeIndent() {
	for i := 0; i < e.indent; i++ {
		e.sb.WriteString("    ")
	}
}
