// Package emit is the Phase 0 C backend. It lowers a type-checked ast.File to a
// single self-contained C translation unit — the shortest path to a binary, and
// the thesis the roadmap's Phase 0 proves (lex -> parse -> sema -> emit C -> cc).
//
// Every Zerg name is emitted with a 'zg_' prefix so it cannot collide with a C
// keyword or the C runtime; the Zerg 'main' becomes 'zg_main', wrapped by a real C
// 'main'. The type universe maps int->int64_t, float->double, bool->bool (stdbool),
// str->const char*. There is no runtime yet: strings are C string literals and
// nothing is refcounted (Phase 0 leaks, per the roadmap).
package emit

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/cmj0121/zerg/src/bootstrap/internal/ast"
	"github.com/cmj0121/zerg/src/bootstrap/internal/diag"
	"github.com/cmj0121/zerg/src/bootstrap/internal/mono"
	"github.com/cmj0121/zerg/src/bootstrap/internal/sema"
	"github.com/cmj0121/zerg/src/bootstrap/internal/token"
)

// Emit lowers the monomorphized program to C source. It renders each instance in
// prog.Funcs, reading the type overlay from prog.Info. When the returned
// diagnostics are non-empty the source is empty and must not be compiled.
func Emit(prog *mono.Program) (string, []diag.Diagnostic) {
	e := &emitter{prog: prog, info: prog.Info}
	e.program()
	if !e.diags.Empty() {
		return "", e.diags.Items()
	}
	return e.sb.String(), nil
}

type emitter struct {
	prog   *mono.Program
	info   *sema.Info
	sb     strings.Builder
	indent int
	diags  diag.List

	// Per-function name environment. Zerg allows a binding to shadow an outer
	// name (e.g. 'mut n := n'), but C parameters and the top-level body share one
	// scope, so every local gets a unique C name; 'scopes' maps a source name to
	// the C name currently in effect and 'used' guarantees uniqueness.
	scopes  []map[string]string
	used    map[string]bool
	counter int
}

func (e *emitter) program() {
	main, ok := e.info.Funcs["main"]
	switch {
	case !ok:
		e.diags.Add(token.Span{}, "no 'main' function to build a program")
		return
	case len(main.Params) != 0:
		e.diags.Add(main.Decl.Span(), "'main' must take no parameters in Phase 0")
	case main.Ret != sema.Nil && main.Ret != sema.Int:
		e.diags.Add(main.Decl.Span(), "'main' must return nil or int in Phase 0")
	}

	e.line("// Generated by zerg (Phase 0). Do not edit.")
	e.line("#include <stdio.h>")
	e.line("#include <stdint.h>")
	e.line("#include <stdbool.h>")
	e.line("#include <string.h>")
	e.blank()

	// prototypes first, so declaration order does not constrain calls
	for _, inst := range e.prog.Funcs {
		e.line(e.prototype(inst) + ";")
	}
	e.blank()

	for _, inst := range e.prog.Funcs {
		e.function(inst)
		e.blank()
	}

	e.cMain(main)
}

// paramList renders a C parameter list ("void" when empty), formatting each of
// the n parameters with render.
func paramList(n int, render func(i int) string) string {
	if n == 0 {
		return "void"
	}
	var b strings.Builder
	for i := 0; i < n; i++ {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(render(i))
	}
	return b.String()
}

// prototype renders a forward declaration with parameter types only, using the
// instance's mangled C name.
func (e *emitter) prototype(inst *mono.Instance) string {
	sig := e.info.Funcs[inst.Origin.Name]
	params := paramList(len(sig.Params), func(i int) string { return cType(sig.Params[i]) })
	return fmt.Sprintf("%s %s(%s)", cType(sig.Ret), inst.Mangled, params)
}

func (e *emitter) function(inst *mono.Instance) {
	fn := inst.Origin
	sig := e.info.Funcs[fn.Name]
	e.used = map[string]bool{}
	e.counter = 0
	e.pushScope() // parameter scope

	params := paramList(len(sig.Params), func(i int) string {
		return cType(sig.Params[i]) + " " + e.declareName(sig.ParamNames[i])
	})
	e.line(fmt.Sprintf("%s %s(%s) {", cType(sig.Ret), inst.Mangled, params))

	e.indent++
	e.pushScope() // body scope, nested so a body binding can shadow a parameter
	for _, s := range fn.Body.Stmts {
		e.stmt(s)
	}
	e.popScope()
	// guarantee a return value on every path for value-returning functions
	if sig.Ret != sema.Nil && !endsWithReturn(fn.Body) {
		e.line("return " + zeroValue(sig.Ret) + ";")
	}
	e.indent--
	e.line("}")

	e.popScope()
}

// endsWithReturn reports whether a block's last statement is an unconditional
// return (a 'return ... if c' may fall through, so it does not count).
func endsWithReturn(b *ast.Block) bool {
	if len(b.Stmts) == 0 {
		return false
	}
	r, ok := b.Stmts[len(b.Stmts)-1].(*ast.ReturnStmt)
	return ok && r.Cond == nil
}

// cMain wraps zg_main in a C entry point.
func (e *emitter) cMain(main *sema.FuncSig) {
	e.line("int main(void) {")
	e.indent++
	if main.Ret == sema.Int {
		e.line("return (int)zg_main();")
	} else {
		e.line("zg_main();")
		e.line("return 0;")
	}
	e.indent--
	e.line("}")
}

// --- statements ---------------------------------------------------------------

func (e *emitter) stmt(s ast.Stmt) {
	switch n := s.(type) {
	case *ast.NopStmt:
		e.line(";")
	case *ast.BindStmt:
		t := e.info.BindTypes[n]
		// resolve the RHS before declaring the name, so 'mut n := n' reads the
		// outer binding (matching ':=' semantics)
		rhs := e.expr(n.Value)
		e.line(fmt.Sprintf("%s %s = %s;", cType(t), e.declareName(n.Name), rhs))
	case *ast.Reassign:
		e.line(fmt.Sprintf("%s = %s;", e.assignTarget(n.Target), e.expr(n.Value)))
	case *ast.PrintStmt:
		e.printStmt(n)
	case *ast.ReturnStmt:
		ret := "return;"
		if n.Value != nil {
			ret = "return " + e.expr(n.Value) + ";"
		}
		if n.Cond != nil {
			e.line(fmt.Sprintf("if (%s) { %s }", e.expr(n.Cond), ret))
		} else {
			e.line(ret)
		}
	case *ast.BreakStmt:
		e.line("break;")
	case *ast.ContinueStmt:
		e.line("continue;")
	case *ast.IfStmt:
		e.ifStmt(n)
	case *ast.ForStmt:
		e.forStmt(n)
	case *ast.ExprStmt:
		e.line(e.expr(n.X) + ";")
	}
}

func (e *emitter) printStmt(n *ast.PrintStmt) {
	v := e.expr(n.Value)
	switch e.info.ExprTypes[n.Value] {
	case sema.Int:
		e.line(fmt.Sprintf("printf(\"%%lld\\n\", (long long)(%s));", v))
	case sema.Float:
		e.line(fmt.Sprintf("printf(\"%%g\\n\", %s);", v))
	case sema.Bool:
		e.line(fmt.Sprintf("printf(\"%%s\\n\", (%s) ? \"true\" : \"false\");", v))
	case sema.Str:
		e.line(fmt.Sprintf("printf(\"%%s\\n\", %s);", v))
	}
}

func (e *emitter) ifStmt(n *ast.IfStmt) {
	for i, br := range n.Branches {
		kw := "if"
		if i > 0 {
			kw = "} else if"
		}
		e.line(fmt.Sprintf("%s (%s) {", kw, e.expr(br.Cond)))
		e.body(br.Body)
	}
	if n.Else != nil {
		e.line("} else {")
		e.body(n.Else)
	}
	e.line("}")
}

func (e *emitter) forStmt(n *ast.ForStmt) {
	if n.Cond == nil {
		e.line("for (;;) {")
	} else {
		e.line(fmt.Sprintf("while (%s) {", e.expr(n.Cond)))
	}
	e.body(n.Body)
	e.line("}")
}

// body emits a block's statements at one deeper indent (the surrounding braces are
// emitted by the caller so 'else' can share a line with the closing brace). It
// opens a nested name scope so the block's bindings do not leak.
func (e *emitter) body(b *ast.Block) {
	e.indent++
	e.pushScope()
	for _, s := range b.Stmts {
		e.stmt(s)
	}
	e.popScope()
	e.indent--
}

// --- name environment ---------------------------------------------------------

func (e *emitter) pushScope() { e.scopes = append(e.scopes, map[string]string{}) }
func (e *emitter) popScope()  { e.scopes = e.scopes[:len(e.scopes)-1] }

// declareName maps a source name to a fresh, function-unique C name (plain
// 'zg_<name>' unless that is already taken, in which case a numeric suffix is
// appended) and records it in the current scope.
func (e *emitter) declareName(name string) string {
	unique := "zg_" + name
	for e.used[unique] {
		e.counter++
		unique = fmt.Sprintf("zg_%s__%d", name, e.counter)
	}
	e.used[unique] = true
	e.scopes[len(e.scopes)-1][name] = unique
	return unique
}

// resolve returns the C name a source name currently refers to.
func (e *emitter) resolve(name string) string {
	for i := len(e.scopes) - 1; i >= 0; i-- {
		if u, ok := e.scopes[i][name]; ok {
			return u
		}
	}
	return "zg_" + name // unreachable for a checked program
}

// --- expressions --------------------------------------------------------------

func (e *emitter) expr(x ast.Expr) string {
	switch n := x.(type) {
	case *ast.IntLit:
		return strconv.FormatInt(n.Value, 10)
	case *ast.FloatLit:
		return floatLiteral(n.Value)
	case *ast.BoolLit:
		if n.Value {
			return "true"
		}
		return "false"
	case *ast.StrLit:
		return cString(n.Value)
	case *ast.NilLit:
		return "0"
	case *ast.Ident:
		return e.resolve(n.Name)
	case *ast.Unary:
		return fmt.Sprintf("(%s%s)", unaryOp(n.Op), e.expr(n.X))
	case *ast.Binary:
		return fmt.Sprintf("(%s %s %s)", e.expr(n.L), binaryOp(n.Op), e.expr(n.R))
	case *ast.Call:
		return e.call(n)
	case *ast.MatchExpr:
		return e.lowerMatch(n)
	default:
		return "0"
	}
}

// lowerMatch lowers a match to a nested C ternary. The subject is a name or
// literal (a Phase 0 restriction), so it is safe to reference in each arm without
// hoisting. The last arm is an unguarded catch-all, forming the final else.
func (e *emitter) lowerMatch(m *ast.MatchExpr) string {
	subj := e.expr(m.Subject)
	subjT := e.info.ExprTypes[m.Subject]
	n := len(m.Arms)
	result := e.armValue(m.Arms[n-1], subj)
	for i := n - 2; i >= 0; i-- {
		test, body := e.armTestAndValue(m.Arms[i], subj, subjT)
		result = fmt.Sprintf("(%s ? %s : %s)", test, body, result)
	}
	return result
}

// armValue emits an arm's body, binding a NamePattern's name to the subject.
func (e *emitter) armValue(arm ast.MatchArm, subj string) string {
	if bp, ok := arm.Pat.(*ast.NamePattern); ok {
		e.pushScope()
		e.scopes[len(e.scopes)-1][bp.Name] = subj
		v := e.expr(arm.Body)
		e.popScope()
		return v
	}
	return e.expr(arm.Body)
}

// armTestAndValue emits an arm's match test and body. A NamePattern's name is in
// scope for both the guard and the body.
func (e *emitter) armTestAndValue(arm ast.MatchArm, subj string, subjT sema.Type) (test, body string) {
	pop := func() {}
	if bp, ok := arm.Pat.(*ast.NamePattern); ok {
		e.pushScope()
		e.scopes[len(e.scopes)-1][bp.Name] = subj
		pop = e.popScope
	}
	test = e.patternTest(arm.Pat, subj, subjT)
	if arm.Guard != nil {
		g := e.expr(arm.Guard)
		if test == "" {
			test = g
		} else {
			test = fmt.Sprintf("(%s && %s)", test, g)
		}
	}
	body = e.expr(arm.Body)
	pop()
	if test == "" {
		test = "1" // a non-last unguarded catch-all is rejected by sema
	}
	return test, body
}

// patternTest renders the boolean C test for a pattern, or "" when the pattern
// matches unconditionally (wildcard or binding).
func (e *emitter) patternTest(pat ast.Pattern, subj string, subjT sema.Type) string {
	lp, ok := pat.(*ast.LitPattern)
	if !ok {
		return ""
	}
	lit := e.expr(lp.Lit)
	if lp.Neg {
		lit = "(-" + lit + ")"
	}
	if subjT == sema.Str {
		return fmt.Sprintf("(strcmp(%s, %s) == 0)", subj, lit)
	}
	return fmt.Sprintf("(%s == %s)", subj, lit)
}

func (e *emitter) call(n *ast.Call) string {
	name := n.Callee.(*ast.Ident).Name
	var args strings.Builder
	for i, a := range n.Args {
		if i > 0 {
			args.WriteString(", ")
		}
		args.WriteString(e.expr(a.Value))
	}
	return fmt.Sprintf("%s(%s)", e.prog.CallTarget(name), args.String())
}

// assignTarget lowers a reassignment target. The Phase 0 backend only lowers the
// bare-identifier lvalue that the checked examples use; richer shapes (tuple,
// struct, field, index) are outside the Phase 0 subset.
func (e *emitter) assignTarget(t ast.AssignTarget) string {
	if lv, ok := t.(*ast.LValueTarget); ok {
		return e.expr(lv.X)
	}
	return "0"
}

// --- lowering helpers ---------------------------------------------------------

func cType(t sema.Type) string {
	switch t {
	case sema.Int:
		return "int64_t"
	case sema.Float:
		return "double"
	case sema.Bool:
		return "bool"
	case sema.Str:
		return "const char*"
	default:
		return "void"
	}
}

func zeroValue(t sema.Type) string {
	switch t {
	case sema.Int:
		return "0"
	case sema.Float:
		return "0.0"
	case sema.Bool:
		return "false"
	case sema.Str:
		return "\"\""
	default:
		return "0"
	}
}

func unaryOp(k token.Kind) string {
	switch k {
	case token.Minus, token.MinusMod:
		return "-"
	case token.Not:
		return "!"
	case token.Tilde:
		return "~"
	}
	return "?"
}

func binaryOp(k token.Kind) string {
	switch k {
	case token.Plus, token.PlusMod:
		return "+"
	case token.Minus, token.MinusMod:
		return "-"
	case token.Star, token.StarMod:
		return "*"
	case token.Slash:
		return "/"
	case token.Percent:
		return "%"
	case token.Amp:
		return "&"
	case token.Pipe:
		return "|"
	case token.Caret:
		return "^"
	case token.Shl:
		return "<<"
	case token.Shr:
		return ">>"
	case token.EqEq:
		return "=="
	case token.Ne:
		return "!="
	case token.Lt:
		return "<"
	case token.Gt:
		return ">"
	case token.Le:
		return "<="
	case token.Ge:
		return ">="
	case token.And:
		return "&&"
	case token.Or:
		return "||"
	}
	return "?"
}

// floatLiteral renders a double literal that C reads as floating-point (always
// carrying a '.' or exponent).
func floatLiteral(v float64) string {
	s := strconv.FormatFloat(v, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eEnN") { // n/N guards inf/nan spellings
		s += ".0"
	}
	return s
}

// cString renders a Go string as a C string literal, escaping conservatively with
// octal for bytes outside printable ASCII so no '\x' run-on can occur.
func cString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c == '\n':
			b.WriteString("\\n")
		case c == '\t':
			b.WriteString("\\t")
		case c == '\r':
			b.WriteString("\\r")
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%03o", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// --- output helpers -----------------------------------------------------------

func (e *emitter) line(s string) {
	e.writeIndent()
	e.sb.WriteString(s)
	e.sb.WriteByte('\n')
}

func (e *emitter) blank() { e.sb.WriteByte('\n') }

func (e *emitter) writeIndent() {
	for i := 0; i < e.indent; i++ {
		e.sb.WriteString("    ")
	}
}
